    
<B> <p style="color:blue;font-size:15px">But we need to know how to learn a computer and what is the main procedure of <I>Machine Learning</I>
<B> <p style="color:brown;font-size:15px">Here is the procedure :
<B> <p style="color:black;font-size:15px">
1. Importing Dataset (Web Scraping)
2. Cleaning Dataset (Delete the Null value or Fill the Null value)
3. Extrating X and y (For cross validation. Here Training_set=80% & Test_set=20%)
4. Train test split (Split into Two set. Where Train_set=(X_train,y_train) and Test_set=(X_teat,y_test))
5. Train
6. Predict
7. Accurcy calculation
8. improve the model
9. Deploy on the website or on the app

# Import Libraries

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [2]:
df=sns.load_dataset('iris')

In [3]:
# Extract your input column and your target(output) column
df['species']=df['species'].replace({'setosa':0,'virginica':1,'versicolor':2})

In [4]:
# Check
df.sample(10)

sepal_length  sepal_width  petal_length  petal_width  species
148           6.2          3.4           5.4          2.3        1
138           6.0          3.0           4.8          1.8        1
147           6.5          3.0           5.2          2.0        1
23            5.1          3.3           1.7          0.5        0
43            5.0          3.5           1.6          0.6        0
149           5.9          3.0           5.1          1.8        1
42            4.4          3.2           1.3          0.2        0
7             5.0          3.4           1.5          0.2        0
146           6.3          2.5           5.0          1.9        1
70            5.9          3.2           4.8          1.8        2

In [5]:
X=df.iloc[:,0:-1].values

In [6]:
# Check
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [7]:
# Check
X.shape

(150, 4)

In [8]:
y=df.iloc[:,-1].values

In [9]:
# Check
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [10]:
y.shape

(150,)

In [11]:
# Split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)

In [12]:
# Check
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(120, 4)
(120,)
(30, 4)
(30,)


In [13]:
# Train your model
from sklearn.tree import DecisionTreeClassifier

In [14]:
clf=DecisionTreeClassifier()

In [15]:
clf.fit(X_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [16]:
clf.predict(np.array([[5.9, 3. , 5.1, 1.8]]))

array([1], dtype=int64)

In [17]:
y_pred=clf.predict(X_test)

In [18]:
y_test

array([0, 2, 2, 0, 1, 2, 1, 0, 0, 1, 2, 0, 1, 2, 2, 0, 2, 2, 0, 0, 2, 2,
       2, 0, 1, 2, 0, 0, 2, 1], dtype=int64)

In [19]:
accuracy_score(y_test,y_pred)

0.9666666666666667